import type { Metadata } from "next";
import localFont from "next/font/local";
import { Revalia } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const revaliaFont = Revalia({
  weight: "400",
  subsets: ["latin"],
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metric = localFont({
  src: "./fonts/metricweb-light.woff2",
  variable: "--font-metric-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${revaliaFont.className} ${metric.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
